import Head from 'next/head'
import Frame from 'components/Frame'
import HomeTabs from 'components/HomeTabs'

export default function Home() {
  return (<>
    <Head>
      <title>Pattmi | 雑誌の目次検索アプリ</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Frame>
      <HomeTabs />
    </Frame>
  </>
  )
}
