import Head from 'next/head'
import Box from '@mui/material/Box'
import Navigation from 'components/Navigation'

type LayoutProps =  {
  children?: React.ReactElement
}

export default function Layout({ children }: LayoutProps):JSX.Element {
  return(<>
    <Head>
      <title>Pattmi | 雑誌の目次検索アプリ</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box
      sx={{
        display: 'flex',
        background: "linear-gradient(216.96deg, rgba(255, 255, 255, 0.2) 4.2%, rgba(255, 255, 255, 0.151042) 8.76%, rgba(0, 0, 0, 0) 23.62%), #2F4858",
        position: "relative",
        zIndex: 1
      }}
    >
      <Navigation />
      <Box component="main" sx={{ flexGrow: 1, maxWidth: 1200, minHeight: '100vh', padding: '4rem' }}>
        {children}
      </Box>
    </Box>
    </>
  )
}